# Generated by Django 6.0.3 on 2026-03-12 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=255)),
                ('eligibility', models.CharField(blank=True, max_length=255)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('application_link', models.URLField(blank=True)),
                ('category', models.CharField(choices=[('internship', 'Internship'), ('job', 'Job'), ('hackathon', 'Hackathon'), ('other', 'Other')], default='other', max_length=32)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_saved', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('saved', 'Saved'), ('applied', 'Applied'), ('expired', 'Expired')], default='saved', max_length=32)),
            ],
            options={
                'ordering': ['deadline', '-created_at'],
            },
        ),
    ]
