# Generated by Django 6.0.3 on 2026-03-12 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpportunityNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=280)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='opportunity',
            name='duplicate_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='summary',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='category',
            field=models.CharField(choices=[('internship', 'Internship'), ('job', 'Job'), ('hackathon', 'Hackathon'), ('scholarship', 'Scholarship'), ('workshop', 'Workshop'), ('other', 'Other')], default='other', max_length=32),
        ),
        migrations.AddIndex(
            model_name='opportunity',
            index=models.Index(fields=['company'], name='opportuniti_company_e106ef_idx'),
        ),
        migrations.AddIndex(
            model_name='opportunity',
            index=models.Index(fields=['deadline'], name='opportuniti_deadlin_294f61_idx'),
        ),
        migrations.AddIndex(
            model_name='opportunity',
            index=models.Index(fields=['category'], name='opportuniti_categor_dd0690_idx'),
        ),
        migrations.AddIndex(
            model_name='opportunity',
            index=models.Index(fields=['company', 'role', 'deadline'], name='opportuniti_company_c6ac5f_idx'),
        ),
        migrations.AddField(
            model_name='opportunitynote',
            name='opportunity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='opportunities.opportunity'),
        ),
    ]
