# Generated by Django 6.0.3 on 2026-03-12 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0002_opportunitynote_opportunity_duplicate_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='duplicate_count',
            field=models.PositiveIntegerField(db_default=0, default=0),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='summary',
            field=models.TextField(blank=True, db_default='', default=''),
        ),
    ]
