# Generated by Django 6.0.3 on 2026-03-12 17:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0004_remove_opportunity_opportuniti_company_c6ac5f_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger_type', models.CharField(choices=[('immediate', 'Immediate'), ('week_before', 'Week Before'), ('three_days', 'Three Days Before'), ('one_day', 'One Day Before')], max_length=32)),
                ('channel', models.CharField(choices=[('email', 'Email'), ('push', 'Push')], max_length=16)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('failed', 'Failed')], max_length=16)),
                ('details', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_logs', to='opportunities.opportunity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'trigger_type', 'channel'], name='opportuniti_user_id_b4ad2c_idx'), models.Index(fields=['opportunity', 'trigger_type', 'channel'], name='opportuniti_opportu_af870a_idx')],
            },
        ),
    ]
