# Generated by Django 6.0.3 on 2026-03-13 06:10

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_devicetoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='calendar_token',
            field=models.CharField(db_index=True, default=uuid.uuid4, editable=False, max_length=64),
        ),
    ]
