# Generated by Django 6.0.3 on 2026-03-13 06:20

import uuid
from django.db import migrations, models


def ensure_unique_calendar_tokens(apps, schema_editor):
    UserProfile = apps.get_model("users", "UserProfile")
    seen = set()
    for profile in UserProfile.objects.all().order_by("id"):
        token = str(profile.calendar_token or "").strip()
        if not token or token in seen:
            token = str(uuid.uuid4())
            while token in seen:
                token = str(uuid.uuid4())
            profile.calendar_token = token
            profile.save(update_fields=["calendar_token"])
        seen.add(token)


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userprofile_calendar_token'),
    ]

    operations = [
        migrations.RunPython(ensure_unique_calendar_tokens, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='userprofile',
            name='calendar_token',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=64, unique=True),
        ),
    ]
